### ISSUE TITLE
Field Overhaul

### ISSUE THREAD

**Issue by mppotter** [AdditiveModeling/pyphasefield#5]
Rework the Field class to be a custom class with a np.ndarray as a member variable.

**Comment by Zhyrek** [comment]
Additional member variables to include within Field:

- pointer to simulation, to access simulation variables
- Name of Field instance, to be used to name plots generated of it
- Color palette for plots, potentially unique per Field instance

**Comment by Zhyrek** [comment]
Completed as of pull request #10
